/* Generated by AN DISI Unibo */ 
package it.unibo.boundaryworker

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Boundaryworker ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val room = location.RoomMap(6,5)
		val gui = adapters.AdapterGui.create("tf25map.txt")
		
		    	val NR = room.getNr()
		    	val NC = room.getNc()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | starts with map NR=$NR NC=$NC")
						CommUtils.outmagenta("$room")
						 clearlog("./logs/ddrboundary.log") 	//vedi src/main/resources/logback.xml  
						 logger.info(  "${currentState.stateName}: starts"  )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="testStep", cond=doswitch() )
				}	 
				state("testStep") { //this:State
					action { //it:State
						 gui.showTheRoom()  
						 gui.displayOnGui(0,0,`it.unibo.kactor`.GuiColors.SUD)  
						 gui.displayOnGui(2,4,`it.unibo.kactor`.GuiColors.TARGET)  
						 gui.displayOnGui(4,3,`it.unibo.kactor`.GuiColors.MAGENTA)  
						delay(1000) 
						CommUtils.outblue("$name | ENDS")
						 System.exit(0)   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
