/* Generated by AN DISI Unibo */ 
package it.unibo.robotsnartusage

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Robotsnartusage ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 val StepTime = 345 
			   var NLAP     = 0		
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name | starts ")
						 clearlog("./logs/robotsmart26usage.log") 			//vedi src/main/resources/logback.xml  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="swing", cond=doswitch() )
				}	 
				state("swing") { //this:State
					action { //it:State
						 logger.info(  "${currentState.stateName}: setrobotstate at HOME"  )  
						forward("setrobotstate", "setpos(0,0,down)" ,"robotsmart" ) 
						 logger.info(  "${currentState.stateName}: move(i)"  )  
						CommUtils.outblue("$name | swing ")
						forward("move", "move(l)" ,"robotsmart" ) 
						delay(500) 
						 logger.info(  "${currentState.stateName}: move(r)"  )  
						forward("move", "move(r)" ,"robotsmart" ) 
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="walkAlomgBoundary", cond=doswitch() )
				}	 
				state("walkAlomgBoundary") { //this:State
					action { //it:State
						CommUtils.outblue("$name | walkAlomgBoundary $NLAP")
						request("step", "step($StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="stepok",cond=whenReply("stepdone"))
					transition(edgeName="t01",targetState="hitwall",cond=whenReply("stepfailed"))
				}	 
				state("stepok") { //this:State
					action { //it:State
						 logger.info(  "${currentState.stateName}: step ddone"  )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="walkAlomgBoundary", cond=doswitch() )
				}	 
				state("hitwall") { //this:State
					action { //it:State
						 var TDONE = "0"  
						if( checkMsgContent( Term.createTerm("stepfailed(DURATION,CAUSE)"), Term.createTerm("stepfailed(T,CAUSE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  TDONE = payloadArg(0)  
								CommUtils.outmagenta("$name | hit wall after: $TDONE")
						}
						 logger.info(  "${currentState.stateName}: step failed $NLAP"  )  
						forward("move", "move(l)" ,"robotsmart" ) 
						 NLAP = NLAP + 1  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="walkAlomgBoundary", cond=doswitchGuarded({ NLAP < 4  
					}) )
					transition( edgeName="goto",targetState="end", cond=doswitchGuarded({! ( NLAP < 4  
					) }) )
				}	 
				state("end") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outblue("$name | BYE ")
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
